/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AchievementId = bigint;
export interface AchievementStatus {
  'achievementId' : AchievementId,
  'unlockedAt' : [] | [Timestamp],
  'unlocked' : boolean,
}
export type GameMode = { 'endless' : null } |
  { 'hardcore' : null } |
  { 'story' : null } |
  { 'bossBattle' : null };
export interface GameSave {
  'weaponLevels' : WeaponLevels,
  'purchaseHistory' : Array<PurchaseRecord>,
  'lastSaved' : Timestamp,
  'unlockedSkins' : Array<SkinId>,
}
export interface LeaderboardEntry {
  'username' : string,
  'player' : Principal,
  'waveReached' : bigint,
  'score' : bigint,
  'timestamp' : Timestamp,
  'gameMode' : GameMode,
}
export interface PlayerProfile {
  'username' : string,
  'lifetimeKills' : bigint,
  'totalXP' : bigint,
  'totalCoins' : bigint,
  'level' : bigint,
}
export interface PurchaseRecord {
  'itemId' : bigint,
  'cost' : bigint,
  'timestamp' : Timestamp,
  'itemType' : { 'skin' : null } |
    { 'powerup' : null } |
    { 'weapon' : null },
}
export type SkinId = bigint;
export interface SubmitScoreRequest {
  'waveReached' : bigint,
  'score' : bigint,
  'gameMode' : GameMode,
}
export type Timestamp = bigint;
export type WeaponLevels = Array<bigint>;
export interface _SERVICE {
  'getAchievements' : ActorMethod<[], Array<AchievementStatus>>,
  'getLeaderboard' : ActorMethod<[], Array<LeaderboardEntry>>,
  'getPlayerProfile' : ActorMethod<[], [] | [PlayerProfile]>,
  'loadGameState' : ActorMethod<[], GameSave>,
  'saveGameState' : ActorMethod<
    [WeaponLevels, Array<SkinId>, Array<PurchaseRecord>],
    undefined
  >,
  'submitScore' : ActorMethod<[SubmitScoreRequest], undefined>,
  'unlockAchievement' : ActorMethod<[AchievementId], boolean>,
  'updatePlayerProfile' : ActorMethod<
    [[] | [string], [] | [bigint], [] | [bigint], [] | [bigint], [] | [bigint]],
    boolean
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];