/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const AchievementId = IDL.Nat;
export const Timestamp = IDL.Int;
export const AchievementStatus = IDL.Record({
  'achievementId' : AchievementId,
  'unlockedAt' : IDL.Opt(Timestamp),
  'unlocked' : IDL.Bool,
});
export const GameMode = IDL.Variant({
  'endless' : IDL.Null,
  'hardcore' : IDL.Null,
  'story' : IDL.Null,
  'bossBattle' : IDL.Null,
});
export const LeaderboardEntry = IDL.Record({
  'username' : IDL.Text,
  'player' : IDL.Principal,
  'waveReached' : IDL.Nat,
  'score' : IDL.Nat,
  'timestamp' : Timestamp,
  'gameMode' : GameMode,
});
export const PlayerProfile = IDL.Record({
  'username' : IDL.Text,
  'lifetimeKills' : IDL.Nat,
  'totalXP' : IDL.Nat,
  'totalCoins' : IDL.Nat,
  'level' : IDL.Nat,
});
export const WeaponLevels = IDL.Vec(IDL.Nat);
export const PurchaseRecord = IDL.Record({
  'itemId' : IDL.Nat,
  'cost' : IDL.Nat,
  'timestamp' : Timestamp,
  'itemType' : IDL.Variant({
    'skin' : IDL.Null,
    'powerup' : IDL.Null,
    'weapon' : IDL.Null,
  }),
});
export const SkinId = IDL.Nat;
export const GameSave = IDL.Record({
  'weaponLevels' : WeaponLevels,
  'purchaseHistory' : IDL.Vec(PurchaseRecord),
  'lastSaved' : Timestamp,
  'unlockedSkins' : IDL.Vec(SkinId),
});
export const SubmitScoreRequest = IDL.Record({
  'waveReached' : IDL.Nat,
  'score' : IDL.Nat,
  'gameMode' : GameMode,
});

export const idlService = IDL.Service({
  'getAchievements' : IDL.Func([], [IDL.Vec(AchievementStatus)], ['query']),
  'getLeaderboard' : IDL.Func([], [IDL.Vec(LeaderboardEntry)], ['query']),
  'getPlayerProfile' : IDL.Func([], [IDL.Opt(PlayerProfile)], ['query']),
  'loadGameState' : IDL.Func([], [GameSave], ['query']),
  'saveGameState' : IDL.Func(
      [WeaponLevels, IDL.Vec(SkinId), IDL.Vec(PurchaseRecord)],
      [],
      [],
    ),
  'submitScore' : IDL.Func([SubmitScoreRequest], [], []),
  'unlockAchievement' : IDL.Func([AchievementId], [IDL.Bool], []),
  'updatePlayerProfile' : IDL.Func(
      [
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Int),
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Nat),
      ],
      [IDL.Bool],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const AchievementId = IDL.Nat;
  const Timestamp = IDL.Int;
  const AchievementStatus = IDL.Record({
    'achievementId' : AchievementId,
    'unlockedAt' : IDL.Opt(Timestamp),
    'unlocked' : IDL.Bool,
  });
  const GameMode = IDL.Variant({
    'endless' : IDL.Null,
    'hardcore' : IDL.Null,
    'story' : IDL.Null,
    'bossBattle' : IDL.Null,
  });
  const LeaderboardEntry = IDL.Record({
    'username' : IDL.Text,
    'player' : IDL.Principal,
    'waveReached' : IDL.Nat,
    'score' : IDL.Nat,
    'timestamp' : Timestamp,
    'gameMode' : GameMode,
  });
  const PlayerProfile = IDL.Record({
    'username' : IDL.Text,
    'lifetimeKills' : IDL.Nat,
    'totalXP' : IDL.Nat,
    'totalCoins' : IDL.Nat,
    'level' : IDL.Nat,
  });
  const WeaponLevels = IDL.Vec(IDL.Nat);
  const PurchaseRecord = IDL.Record({
    'itemId' : IDL.Nat,
    'cost' : IDL.Nat,
    'timestamp' : Timestamp,
    'itemType' : IDL.Variant({
      'skin' : IDL.Null,
      'powerup' : IDL.Null,
      'weapon' : IDL.Null,
    }),
  });
  const SkinId = IDL.Nat;
  const GameSave = IDL.Record({
    'weaponLevels' : WeaponLevels,
    'purchaseHistory' : IDL.Vec(PurchaseRecord),
    'lastSaved' : Timestamp,
    'unlockedSkins' : IDL.Vec(SkinId),
  });
  const SubmitScoreRequest = IDL.Record({
    'waveReached' : IDL.Nat,
    'score' : IDL.Nat,
    'gameMode' : GameMode,
  });
  
  return IDL.Service({
    'getAchievements' : IDL.Func([], [IDL.Vec(AchievementStatus)], ['query']),
    'getLeaderboard' : IDL.Func([], [IDL.Vec(LeaderboardEntry)], ['query']),
    'getPlayerProfile' : IDL.Func([], [IDL.Opt(PlayerProfile)], ['query']),
    'loadGameState' : IDL.Func([], [GameSave], ['query']),
    'saveGameState' : IDL.Func(
        [WeaponLevels, IDL.Vec(SkinId), IDL.Vec(PurchaseRecord)],
        [],
        [],
      ),
    'submitScore' : IDL.Func([SubmitScoreRequest], [], []),
    'unlockAchievement' : IDL.Func([AchievementId], [IDL.Bool], []),
    'updatePlayerProfile' : IDL.Func(
        [
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Int),
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Nat),
        ],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };