/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface LeaderboardEntry {
    username: string;
    player: Principal;
    waveReached: bigint;
    score: bigint;
    timestamp: Timestamp;
    gameMode: GameMode;
}
export type Timestamp = bigint;
export interface SubmitScoreRequest {
    waveReached: bigint;
    score: bigint;
    gameMode: GameMode;
}
export interface AchievementStatus {
    achievementId: AchievementId;
    unlockedAt?: Timestamp;
    unlocked: boolean;
}
export interface PurchaseRecord {
    itemId: bigint;
    cost: bigint;
    timestamp: Timestamp;
    itemType: Variant_skin_powerup_weapon;
}
export interface PlayerProfile {
    username: string;
    lifetimeKills: bigint;
    totalXP: bigint;
    totalCoins: bigint;
    level: bigint;
}
export type WeaponLevels = Array<bigint>;
export type SkinId = bigint;
export type AchievementId = bigint;
export interface GameSave {
    weaponLevels: WeaponLevels;
    purchaseHistory: Array<PurchaseRecord>;
    lastSaved: Timestamp;
    unlockedSkins: Array<SkinId>;
}
export enum GameMode {
    endless = "endless",
    hardcore = "hardcore",
    story = "story",
    bossBattle = "bossBattle"
}
export enum Variant_skin_powerup_weapon {
    skin = "skin",
    powerup = "powerup",
    weapon = "weapon"
}
export interface backendInterface {
    getAchievements(): Promise<Array<AchievementStatus>>;
    getLeaderboard(): Promise<Array<LeaderboardEntry>>;
    getPlayerProfile(): Promise<PlayerProfile | null>;
    loadGameState(): Promise<GameSave>;
    saveGameState(weaponLevels: WeaponLevels, unlockedSkins: Array<SkinId>, purchaseHistory: Array<PurchaseRecord>): Promise<void>;
    submitScore(req: SubmitScoreRequest): Promise<void>;
    unlockAchievement(achievementId: AchievementId): Promise<boolean>;
    updatePlayerProfile(username: string | null, levelDelta: bigint | null, coinsDelta: bigint | null, xpDelta: bigint | null, killsDelta: bigint | null): Promise<boolean>;
}
import type { AchievementId as _AchievementId, AchievementStatus as _AchievementStatus, GameMode as _GameMode, GameSave as _GameSave, LeaderboardEntry as _LeaderboardEntry, PlayerProfile as _PlayerProfile, PurchaseRecord as _PurchaseRecord, SkinId as _SkinId, SubmitScoreRequest as _SubmitScoreRequest, Timestamp as _Timestamp, WeaponLevels as _WeaponLevels } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async getAchievements(): Promise<Array<AchievementStatus>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAchievements();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAchievements();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLeaderboard(): Promise<Array<LeaderboardEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeaderboard();
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeaderboard();
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPlayerProfile(): Promise<PlayerProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlayerProfile();
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlayerProfile();
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async loadGameState(): Promise<GameSave> {
        if (this.processError) {
            try {
                const result = await this.actor.loadGameState();
                return from_candid_GameSave_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.loadGameState();
            return from_candid_GameSave_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveGameState(arg0: WeaponLevels, arg1: Array<SkinId>, arg2: Array<PurchaseRecord>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveGameState(arg0, arg1, to_candid_vec_n17(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveGameState(arg0, arg1, to_candid_vec_n17(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async submitScore(arg0: SubmitScoreRequest): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitScore(to_candid_SubmitScoreRequest_n21(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitScore(to_candid_SubmitScoreRequest_n21(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async unlockAchievement(arg0: AchievementId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.unlockAchievement(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unlockAchievement(arg0);
            return result;
        }
    }
    async updatePlayerProfile(arg0: string | null, arg1: bigint | null, arg2: bigint | null, arg3: bigint | null, arg4: bigint | null): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePlayerProfile(to_candid_opt_n25(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n26(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n27(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n26(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n26(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePlayerProfile(to_candid_opt_n25(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n26(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n27(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n26(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n26(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
}
function from_candid_AchievementStatus_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AchievementStatus): AchievementStatus {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_GameMode_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GameMode): GameMode {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_GameSave_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GameSave): GameSave {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_LeaderboardEntry_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LeaderboardEntry): LeaderboardEntry {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_PurchaseRecord_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PurchaseRecord): PurchaseRecord {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PlayerProfile]): PlayerProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Timestamp]): Timestamp | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    weaponLevels: _WeaponLevels;
    purchaseHistory: Array<_PurchaseRecord>;
    lastSaved: _Timestamp;
    unlockedSkins: Array<_SkinId>;
}): {
    weaponLevels: WeaponLevels;
    purchaseHistory: Array<PurchaseRecord>;
    lastSaved: Timestamp;
    unlockedSkins: Array<SkinId>;
} {
    return {
        weaponLevels: value.weaponLevels,
        purchaseHistory: from_candid_vec_n13(_uploadFile, _downloadFile, value.purchaseHistory),
        lastSaved: value.lastSaved,
        unlockedSkins: value.unlockedSkins
    };
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    itemId: bigint;
    cost: bigint;
    timestamp: _Timestamp;
    itemType: {
        skin: null;
    } | {
        powerup: null;
    } | {
        weapon: null;
    };
}): {
    itemId: bigint;
    cost: bigint;
    timestamp: Timestamp;
    itemType: Variant_skin_powerup_weapon;
} {
    return {
        itemId: value.itemId,
        cost: value.cost,
        timestamp: value.timestamp,
        itemType: from_candid_variant_n16(_uploadFile, _downloadFile, value.itemType)
    };
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    achievementId: _AchievementId;
    unlockedAt: [] | [_Timestamp];
    unlocked: boolean;
}): {
    achievementId: AchievementId;
    unlockedAt?: Timestamp;
    unlocked: boolean;
} {
    return {
        achievementId: value.achievementId,
        unlockedAt: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.unlockedAt)),
        unlocked: value.unlocked
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    username: string;
    player: Principal;
    waveReached: bigint;
    score: bigint;
    timestamp: _Timestamp;
    gameMode: _GameMode;
}): {
    username: string;
    player: Principal;
    waveReached: bigint;
    score: bigint;
    timestamp: Timestamp;
    gameMode: GameMode;
} {
    return {
        username: value.username,
        player: value.player,
        waveReached: value.waveReached,
        score: value.score,
        timestamp: value.timestamp,
        gameMode: from_candid_GameMode_n8(_uploadFile, _downloadFile, value.gameMode)
    };
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    skin: null;
} | {
    powerup: null;
} | {
    weapon: null;
}): Variant_skin_powerup_weapon {
    return "skin" in value ? Variant_skin_powerup_weapon.skin : "powerup" in value ? Variant_skin_powerup_weapon.powerup : "weapon" in value ? Variant_skin_powerup_weapon.weapon : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    endless: null;
} | {
    hardcore: null;
} | {
    story: null;
} | {
    bossBattle: null;
}): GameMode {
    return "endless" in value ? GameMode.endless : "hardcore" in value ? GameMode.hardcore : "story" in value ? GameMode.story : "bossBattle" in value ? GameMode.bossBattle : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AchievementStatus>): Array<AchievementStatus> {
    return value.map((x)=>from_candid_AchievementStatus_n2(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PurchaseRecord>): Array<PurchaseRecord> {
    return value.map((x)=>from_candid_PurchaseRecord_n14(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_LeaderboardEntry>): Array<LeaderboardEntry> {
    return value.map((x)=>from_candid_LeaderboardEntry_n6(_uploadFile, _downloadFile, x));
}
function to_candid_GameMode_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GameMode): _GameMode {
    return to_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function to_candid_PurchaseRecord_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PurchaseRecord): _PurchaseRecord {
    return to_candid_record_n19(_uploadFile, _downloadFile, value);
}
function to_candid_SubmitScoreRequest_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SubmitScoreRequest): _SubmitScoreRequest {
    return to_candid_record_n22(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    itemId: bigint;
    cost: bigint;
    timestamp: Timestamp;
    itemType: Variant_skin_powerup_weapon;
}): {
    itemId: bigint;
    cost: bigint;
    timestamp: _Timestamp;
    itemType: {
        skin: null;
    } | {
        powerup: null;
    } | {
        weapon: null;
    };
} {
    return {
        itemId: value.itemId,
        cost: value.cost,
        timestamp: value.timestamp,
        itemType: to_candid_variant_n20(_uploadFile, _downloadFile, value.itemType)
    };
}
function to_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    waveReached: bigint;
    score: bigint;
    gameMode: GameMode;
}): {
    waveReached: bigint;
    score: bigint;
    gameMode: _GameMode;
} {
    return {
        waveReached: value.waveReached,
        score: value.score,
        gameMode: to_candid_GameMode_n23(_uploadFile, _downloadFile, value.gameMode)
    };
}
function to_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_skin_powerup_weapon): {
    skin: null;
} | {
    powerup: null;
} | {
    weapon: null;
} {
    return value == Variant_skin_powerup_weapon.skin ? {
        skin: null
    } : value == Variant_skin_powerup_weapon.powerup ? {
        powerup: null
    } : value == Variant_skin_powerup_weapon.weapon ? {
        weapon: null
    } : value;
}
function to_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GameMode): {
    endless: null;
} | {
    hardcore: null;
} | {
    story: null;
} | {
    bossBattle: null;
} {
    return value == GameMode.endless ? {
        endless: null
    } : value == GameMode.hardcore ? {
        hardcore: null
    } : value == GameMode.story ? {
        story: null
    } : value == GameMode.bossBattle ? {
        bossBattle: null
    } : value;
}
function to_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<PurchaseRecord>): Array<_PurchaseRecord> {
    return value.map((x)=>to_candid_PurchaseRecord_n18(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
